# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\User\Desktop\BinanceDownloader\quant\gui\widgets\GraphForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GraphForm(object):
    def setupUi(self, GraphForm):
        GraphForm.setObjectName("GraphForm")
        GraphForm.resize(800, 600)
        self.gridLayout = QtWidgets.QGridLayout(GraphForm)
        self.gridLayout.setObjectName("gridLayout")
        self.graphicsView = QtWidgets.QGraphicsView(GraphForm)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 0, 0, 1, 1)

        self.retranslateUi(GraphForm)
        QtCore.QMetaObject.connectSlotsByName(GraphForm)

    def retranslateUi(self, GraphForm):
        _translate = QtCore.QCoreApplication.translate
        GraphForm.setWindowTitle(_translate("GraphForm", "Form"))
